### ISSUE TITLE
Components Flexibility

### ISSUE THREAD

**Issue by firmai** [balajissp/dash-shap-components#1]
Hi there, I really like your components, I have a quick question, do you perhaps know if there is a way for me to change the color of the text, as I have a dark background. 
![image](https://user-images.githubusercontent.com/26666267/116867585-612bb380-ac05-11eb-8d6c-0454ba93d59c.png)

Thanks again for the component.

**Comment by balajissp** [comment]
Hi, thanks for using the component! 

the text color is same as the arrows, which can be customised with the plot_cmap argument: https://github.com/balajissp/dash-shap-components/blob/15476ac617c14fd5fbd6d06c5431889bb8ef6257/dash_shap_components/ForcePlot.py#L21-L25 

Hope that helps!
